### ISSUE TITLE
"Permission denied for current user to access the robots action" for anonymous users

### ISSUE THREAD

**Issue by matt-bernhardt** [ivyrze/omeka-s-module-robots#1]
When I enable this module, I can see the robots.txt file from a browser when I'm logged in, but when I switch to a private window or try to get it via curl, I get a 500 error code?

This is what I see in the terminal (trying to get to a local Lando environment, so that domain won't work obviously)
```bash
% curl -I http://exhibits.lndo.site/robots.txt 
HTTP/1.1 500 Internal Server Error
Cache-Control: no-store, no-cache, must-revalidate
Content-Type: text/html; charset=UTF-8
Date: Thu, 28 Mar 2024 15:08:41 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Server: Apache/2.4.56 (Debian)
Set-Cookie: 464ce40ad862fb86903b332ab61dfc78=3a386fdf7488aef45e68eec9aa011b70; path=/; HttpOnly
X-Powered-By: PHP/8.2.5
```

When I look in the log stream, I see these messages:
```
appserver_1  | [Thu Mar 28 15:08:41.728710 2024] [php:notice] [pid 5856] [client 172.24.0.2:34668] 
Omeka\\Mvc\\Exception\\PermissionDeniedException: Permission denied for the current user to access the robots action of the Robots\\Controller\\Robots controller. in /app/web/application/src/Mvc/MvcListeners.php:463
Stack trace:
#0 /app/web/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Omeka\\Mvc\\MvcListeners->authorizeUserAgainstController(Object(Laminas\\Mvc\\MvcEvent))
#1 /app/web/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\\EventManager\\EventManager->triggerListeners(Object(Laminas\\Mvc\\MvcEvent), Object(Closure))
#2 /app/web/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\\EventManager\\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\\Mvc\\MvcEvent))
#3 /app/web/index.php(21): Laminas\\Mvc\\Application->run()
#4 {main}

appserver_1  | 172.24.0.2 - - [28/Mar/2024:15:08:41 +0000] "HEAD /robots.txt HTTP/1.1" 500 398 "-" "curl/8.4.0"
```

Is there something I should be doing in the configuration of this module to prevent this problem from occurring? Based on the log stream messages, I don't think this is being caused by the interactions with any other module or the theme I'm using - but I might be missing something.

**Comment by ivyrze** [comment]
Thanks for flagging this. I just pushed a fix and will be releasing a new version shortly. Let me know if it still gives you any issues!

**Comment by matt-bernhardt** [comment]
Great, thanks! my local application seems to work as expected now. Much appreciated!
